-- PostgreSQL setup is automatic when the backend starts.
--
-- For Railway, link a PostgreSQL service to the backend service and use the
-- generated DATABASE_URL. For local PostgreSQL, create a database and set:
-- DATABASE_URL=postgresql://postgres:<password>@localhost:5432/novarix
--
-- The canonical schema is applied by backend/src/models/db.js from:
-- backend/database/supabase/schema.sql
